"""add language to post

Revision ID: 10396f71ebec
Revises: 4cd79cd045e7
Create Date: 2020-11-15 21:27:47.616948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10396f71ebec'
down_revision = '4cd79cd045e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
